# Generated by Django 3.2.16 on 2023-03-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=True, max_length=20)),
                ('answer', models.TextField(default=True, max_length=100)),
            ],
        ),
    ]
