# Generated by Django 3.2.16 on 2023-04-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='adhaar',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='age',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='job',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='memberGen',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
