# Generated by Django 3.2.16 on 2023-05-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_buy_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_energy',
            name='cus_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='buy_energy',
            name='energy_price',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='buy_energy',
            name='meter_id',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='buy_energy',
            name='quantity',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
