# Generated by Django 3.2.6 on 2023-05-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230524_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='meter_analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.CharField(default=True, max_length=5)),
            ],
        ),
    ]
