# Generated by Django 3.2.6 on 2023-07-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_meter_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='summary_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default=False, max_length=10)),
                ('uploadAudio', models.FileField(default=False, upload_to='new_audio/')),
            ],
        ),
    ]
