# Generated by Django 3.2.6 on 2023-07-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_summary_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='meta_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv_name', models.CharField(default=False, max_length=10)),
                ('uploadVideo', models.FileField(default=False, upload_to='new_video/')),
            ],
        ),
    ]
