# Generated by Django 3.2.6 on 2023-07-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_meta_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=True, max_length=20)),
                ('answer', models.TextField(default=True, max_length=500)),
            ],
        ),
    ]
