# Generated by Django 3.2.6 on 2023-07-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary_file',
            name='slider_value',
            field=models.IntegerField(default=True),
        ),
    ]
