# Generated by Django 3.2.6 on 2023-07-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_ipfs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipfs',
            name='f_hash',
            field=models.TextField(default=True, max_length=100),
        ),
    ]
