# Generated by Django 3.2.6 on 2023-07-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_cloud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloud',
            old_name='p_id',
            new_name='p_num',
        ),
        migrations.AddField(
            model_name='cloud',
            name='p_name',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
