# Generated by Django 3.2.6 on 2023-07-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20230728_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta_video',
            name='uploadVideo',
        ),
        migrations.AddField(
            model_name='meta_video',
            name='pv_num',
            field=models.BigIntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='summary_file',
            name='p_num',
            field=models.BigIntegerField(default=True),
        ),
    ]
